### ISSUE TITLE
U-2-Net模型导入时报错

### ISSUE THREAD

**Issue by linxiaohui** [linxiaohui/image-service#1]
> Traceback (most recent call last):
  File "u2net_rpc.py", line 63, in <module>
    NET.load_state_dict(**torch.load(MODEL_DIR)**)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 88, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 70, in _cuda_deserialize
    return obj.cuda(device)
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 68, in _cuda
    with torch.cuda.device(device):
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 225, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
**AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'**

**Comment by linxiaohui** [comment]
```
# CPU->CPU,GPU->GPU
torch.load('gen_500000.pkl')  
# GPU->CPU
torch.load('gen_500000.pkl', map_location=lambda storage, loc: storage)  
# CPU->GPU1
torch.load('gen_500000.pkl', map_location=lambda storage, loc: storage.cuda(1))
```

**Comment by linxiaohui** [comment]
`torch.load(file, map_location='cpu')`
