### ISSUE TITLE
FaceSketch: 加载模型时报错

### ISSUE THREAD

**Issue by linxiaohui** [linxiaohui/image-service#4]
> Traceback (most recent call last):
  File "/face_sketch.py", line 58, in <module>
    NET.load_state_dict(torch.load(MODEL_DIR,  map_location='cpu'))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for U2NET:
	Unexpected key(s) in state_dict: "stage1.rebnconvin.bn_s1.num_batches_tracked", "stage1.rebnconv1.bn_s1.num_batches_tracked", "stage1.rebnconv2.bn_s1.num_batches_tracked", "stage1.rebnconv3.bn_s1.num_batches_tracked", "stage1.rebnconv4.bn_s1.num_batches_tracked", "stage1.rebnconv5.bn_s1.num_batches_tracked", "stage1.rebnconv6.bn_s1.num_batches_tracked", "stage1.rebnconv7.bn_s

**Comment by linxiaohui** [comment]
原因是使用pytorch 1.0.0 版本训练的；而docker镜像构建时，按照U-2-Net的"标准"使用的 pytorch 0.4
