### ISSUE TITLE
UnicodeEncodeError in Docker 容器中

### ISSUE THREAD

**Issue by linxiaohui** [linxiaohui/image-service#48]
`
[E 201221 14:10:29 web:1793] Uncaught exception POST /beauty_score.html (172.17.0.1)
    HTTPServerRequest(protocol='http', host='www.5190m.top:65535', method='POST', uri='/beauty_score.html', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "image_service.py", line 35, in get_baidu_score
        ak = os.environ['BAIDU_AIP_AK']
      File "/usr/lib/python3.6/os.py", line 669, in __getitem__
        raise KeyError(key) from None
    KeyError: 'BAIDU_AIP_AK'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "image_service.py", line 135, in post
        baidu_score = get_baidu_score(image_uuid, data)
      File "image_service.py", line 38, in get_baidu_score
        print("\u6ca1\u6709\u914d\u7f6eBaidu AI\u5e73\u53f0\u7684Key", e1)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
`

**Comment by linxiaohui** [comment]
参见 [Docker容器中运行Python程序报UnicodeEncodeError异常](http://5190m.top/2020/11/26/2020-11-26-python3-in-docker-unicode-error/)
